<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>it.uninsubria</groupId>
    <artifactId>theknife</artifactId>
    <version>1.0.0</version>
    <packaging>jar</packaging>

    <name>TheKnife</name>
    <description>Piattaforma client/server per la ricerca e recensione di ristoranti - Laboratorio Interdisciplinare B</description>

    <properties>
        <maven.compiler.release>21</maven.compiler.release>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <javafx.version>21.0.4</javafx.version>
    </properties>

    <dependencies>
        <!-- Driver JDBC PostgreSQL (server) -->
        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <version>42.7.4</version>
        </dependency>
</project>